---
abstract: 'Powertools for MySQL databases'
author:
  - 'Nic Sandfield <niczero@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojar-Mysql
no_index:
  directory:
    - t
    - inc
    - test
requires:
  DBD::mysql: 3.0008
  DBI: 1.53
  Mojolicious: 3.33
  perl: 5.010001
resources:
  bugtracker: http://github.com/niczero/mojar-mysql/issues
  homepage: http://niczero.github.com/mojar-mysql
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: http://github.com/niczero/mojar-mysql
version: 2.034
